services:
  - postgresql
  - docker
matrix:
  include:
    - language: node_js
      node_js: node
      addons:
        apt:
          packages:
            - libgconf-2-4
      cache:
        npm: true
        directories:
          - ~/.cache
      before_script:
        - cd atcoder-problems-frontend/
      script:
        - npm install yarn -g
        - yarn
        - yarn build
        - yarn prepare-ci
        - yarn start:ci &
        - yarn cypress:run
