# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm install yarn -g
      - run: sudo apt-get install libgconf-2-4
      - run: |
          cd atcoder-problems-frontend
          yarn
          yarn build
          yarn prepare-ci
          yarn start:ci &
          yarn cypress:run
      - name: Pack results
        if: always()
        run: |
          cd atcoder-problems-frontend
          mkdir cypress_results
          cp -rf cypress/screenshots cypress_results || true
          cp -rf cypress/videos cypress_results || true
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress_results
          path: atcoder-problems-frontend/cypress_results
